import { Project } from './interfaces/Project';

export const projectsData: Project[] = [
  {
    id: 1,
    name: 'پروژه ساخت مسکن تهران',
    type: 'مسکن',
    province: 'تهران',
    lat: 35.6892,
    lng: 51.3890,
    image: 'https://example.com/images/project1.jpg',
    description: 'این پروژه شامل ساخت مسکن‌های مدرن در شهر تهران است.',
  },
  {
    id: 2,
    name: 'پروژه ساخت پل اصفهان',
    type: 'راه‌سازی',
    province: 'اصفهان',
    lat: 32.6546,
    lng: 51.6680,
    image: 'https://example.com/images/project2.jpg',
    description: 'پروژه ساخت پل جدید در شهر اصفهان برای بهبود ترافیک شهری.',
  },
  {
    id: 3,
    name: 'پروژه ساخت بیمارستان شیراز',
    type: 'بیمارستان',
    province: 'فارس',
    lat: 29.5918,
    lng: 52.5836,
    image: 'https://example.com/images/project3.jpg',
    description: 'ساخت بیمارستان جدید با تجهیزات پیشرفته در شهر شیراز.',
  },
  {
    id: 4,
    name: 'پروژه ساخت مدرسه تبریز',
    type: 'آموزشی',
    province: 'آذربایجان شرقی',
    lat: 38.0667,
    lng: 46.2993,
    image: 'https://example.com/images/project4.jpg',
    description: 'پروژه ساخت مدرسه مدرن در شهر تبریز برای ارتقاء سطح آموزشی.',
  },
  {
    id: 5,
    name: 'پروژه ساخت پارک مشهد',
    type: 'فضای سبز',
    province: 'خراسان رضوی',
    lat: 36.2605,
    lng: 59.6168,
    image: 'https://example.com/images/project5.jpg',
    description: 'پروژه ساخت پارک و فضای سبز جدید در شهر مشهد.',
  },
];